---
default:
  adapter: 'postgresql'
  encoding: unicode
  pool: <%= ENV["DB_POOL"] || 5 %>

development:
  adapter: 'postgresql'
  database: spot_hyper_development
  encoding: unicode
  pool: <%= ENV["DB_POOL"] || 5 %>

production:
  adapter: 'postgresql'
  database: spot_hyper_production
  encoding: unicode
  pool: <%= ENV["DB_POOL"] || 50 %>

staging:
  adapter: 'postgresql'
  database: spot_hyper_staging
  encoding: unicode
  pool: <%= ENV["DB_POOL"] || 50 %>
